import React from 'react';

const Disclaimer: React.FC = () => {
    return (
        <div className="max-w-4xl mx-auto py-12 space-y-12">
            <div className="space-y-4">
                <h1 className="text-5xl font-bold">Legal Disclaimer</h1>
                <p className="text-zinc-400 text-lg">Please read these terms carefully before using DocuGuard Services.</p>
            </div>

            <div className="glass p-10 rounded-3xl space-y-8 leading-relaxed text-zinc-300">
                <section className="space-y-4">
                    <h2 className="text-2xl font-bold text-white">1. AI Analysis Limitations</h2>
                    <p>
                        DocuGuard utilizes advanced machine learning and artificial intelligence to analyze documents. While we strive for absolute accuracy, the results provided are probabilistic in nature. DocuGuard does not provide a 100% guarantee of document authenticity or fraud detection.
                    </p>
                </section>

                <section className="space-y-4">
                    <h2 className="text-2xl font-bold text-white">2. Not Legal Advice</h2>
                    <p>
                        The information generated by our forensics engine is for analysis purposes only and does not constitute legal, financial, or professional advice. Users should consult with qualified legal counsel or certified forensic experts before taking any action based on DocuGuard reports.
                    </p>
                </section>

                <section className="space-y-4">
                    <h2 className="text-2xl font-bold text-white">3. User Responsibility</h2>
                    <p>
                        Users are solely responsible for the documents they upload. By using this platform, you warrant that you have the right to analyze the provided documents and that your use of the service complies with all applicable privacy and data protection laws.
                    </p>
                </section>

                <section className="space-y-4 border-t border-zinc-800 pt-8">
                    <p className="text-sm text-zinc-500">
                        Last updated: February 22, 2026. DocuGuard is a registered trademark of the Advanced Forensics Group.
                    </p>
                </section>
            </div>
        </div>
    );
};

export default Disclaimer;
